### ISSUE TITLE
News Detail Title

### ISSUE THREAD

**Issue by craigmacgregor** [NAVCoin/NavHub#16]
The News Detail page doesn't display the title of the news article.

e.g. this page: https://www.navcore.org/news/2018/04/navcoin-community-hub-launched/

should display the title "NavCoin Community Hub Launched, Alex visits Auckland."

**Comment by matt-auckland** [comment]
This doesn't seem to be an issue anymore? Can we close this

**Comment by craigmacgregor** [comment]
this is still an issue.
