### ISSUE TITLE
Update the README.md so that the site's purpose is clearer

### ISSUE THREAD

**Issue by matt-auckland** [navcoin/NavHub#171]
### Description

Update this initial blurb so it actually tells people useful information.

### Motivation

Currently the purpose of the NavHub site is not clear from the readme.

![image](https://user-images.githubusercontent.com/12672050/56260724-6efc6200-612c-11e9-9127-4f1837bc82f9.png)

### Acceptance Criteria

- [ ] Description is satisfied.

**Comment by JanMooMoo** [comment]
can i have this?
