### ISSUE TITLE
Enable site translations on NavHub

### ISSUE THREAD

**Issue by proletesseract** [navcoin/NavHub#266]
### Description
Currently NavHub is only displayed in english, there should be multiple language translations like on navcoin.org

### Motivation
Increase access to the site for non-english readers.

### Acceptance Criteria

- [ ] Language switcher is available in the menu.
- [ ] At least one language translation is added (suggestion: spanish).
- [ ] Changes display correctly on desktop / mobile.
- [ ] Translations have been added or ammended as necessary.

**Comment by will987456** [comment]
Hello sir,
How can I participate in this project?
I'm from Korea and do you need a translation into Korean as well ? 

Many Thanks,
